### ISSUE TITLE
mitchify the popup

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/swi#113]
ask @HansVraga for the general idea of what we're looking for

**Comment by HansVraga** [comment]
@mitch-wim -
The new lobi-panel pop-up is a bit rough around the edges, and there is a lot of flexibility on how it could look. You can preview it (before grabbing the latest branch) here: https://fwsprimary.wim.usgs.gov/swi-dev/ (and zooming in significantly to click on individual wetland polygons) Please specifically address:

- [ ] Loading animation when the user clicks "Report" (it's cut off - we're not sure why)
- [ ] Viewing all the content (typically a long list of links) within the Reports tab - can we make the individual items a bit more read-able (one suggestion alternating backgrounds?)

There is flexibility in altering the size of the pop-up and a lot more - feel free to make changes at your discretion and we'll take a look when you're done. 

If you have questions I can discuss - but wanted to get this detailed note in now as I don't know if you'll get to this task for a few days...

**Comment by mitch-wim** [comment]
Note to self 📝

Spacing between report links / more readable
