### ISSUE TITLE
Error when running .NET aspx code from FWS (halp)

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/swi#121]
We've been hosting and running wetlands decoders for FWS for years now. They recently updated their code and db file type and now I'm getting errors. 

The current one running is the old style with .mdb db and can be tested here:

https://fwsprimary.wim.usgs.gov/decoders/wetlands.aspx?CodeURL=R2UBH

You have to click the 'DECODE' button to see the results.

The new one with .accdb db can be tested here:

https://fwsprimary.wim.usgs.gov/decoders/temp/wetlands.aspx?CodeURL=R2UBH

Click 'CLICK HERE TO DECODE' to run the code and see there is a generic error.

Running it locally on fwsprimary with the following URL has the more specific error:

https://localhost/decoders/temp/wetlands.aspx?CodeURL=R2UBH

![image_8](https://user-images.githubusercontent.com/5325440/32292619-ef3decb8-befd-11e7-8970-85521b833f0e.png)
☝️ that's what I get with the localhost call.

I attempted to install what I thought was the correct redistributable found [here](https://www.microsoft.com/en-us/download/details.aspx?id=54920), but 🚳 

Obi-wan, you're my only hope.

**Comment by aaronstephenson** [comment]
I think I fixed it? When I click "Decode", I get data back and no errors.

All I did was uninstall the two 64-bit engine redistributables and install the 2010 32-bit redistributable and restart IIS. I'm guessing that the Access DBs (accdb) are 32-bit and could only be read by a 32-bit engine? Just a wild guess.

In any case, it's working now!

**Comment by njestes** [comment]
That must have been it, THANKS!

I'll leave it to you to close up whenever you're ready to call it.
