### ISSUE TITLE
Wetlands WMS service outage - large C drive

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/swi#173]
We lost the Wetlands WMS service (and REST service, briefly) due to a full C: drive on the system. 
We should either look into ways to keep the C: Drive clear (scripts to clear out logs / cache / etc?) or increase the size of the C: drive.

**Comment by aaronstephenson** [comment]
Increasing the size of the drive is the most practical solution I think, but it's going to require downtime while the hard drive swap occurs. Any particular time when that would be OK to do @HansVraga?

**Comment by njestes** [comment]
@aaronstephenson I don't think any particular time is best. Don't think it's necessary to do it outside of work hours either. So, maybe a little later in the day, but that's a marginally better time. So, if it easiest done manually, then I'd say whenever is probably fine. @HansVraga ?

**Comment by aaronstephenson** [comment]
Also, which server, Primary or Public or both?

**Comment by HansVraga** [comment]
No issues noted on the server serving the website, just the public services (unless @njestes observed something different).

Agreed with Nick's thoughts about timing - if we're talking a couple of minutes I don't think it will matter all that much.

**Comment by aaronstephenson** [comment]
Doing it now.

**Comment by njestes** [comment]
Let's up the Primary C drive too. It's better off, but still inching closer to failure every day.

**Comment by aaronstephenson** [comment]
I bumped both from 100GB to 140GB. The process is sure taking its sweet time, though, only at 10% done after 10 minutes.

**Comment by aaronstephenson** [comment]
Took a while, and required a reboot, but the C drives now look to have plenty of space.

**Comment by njestes** [comment]
@aaronstephenson @DanielJBeckman reopened this, because I think it'll require more than a larger C drive. Twice now in the last month, a temp appdata folder for the arcgis user has filled the C drive with in about 2 weeks, causing the services to become unresponsive. 

I think we should set up some kind of scheduled task that clears this directory out every day or every few days. Thoughts?

**Comment by aaronstephenson** [comment]
I agree, a script is the next step. Ideally we would try to find out how this is happening in the first place, and perhaps implement some kind of throttling based on IP address or something, but that would require a lot of effort.

@DanielJBeckman could you write this script to empty the `C:\Users\arcgis\AppData\Local\Temp` folder and schedule it in Windows Task Scheduler? I'm thinking just a simple .bat file or even a Python script. I've written several in the past so let me know if you need any help.

@njestes how often do you want that directory cleared out?

**Comment by njestes** [comment]
Let's see ... how about every day, but keep any files created within the last 24 hours.

**Comment by HansVraga** [comment]
Housekeeping note: FWS Wetlands folks will need to be notified when we've got this periodic clean-up scheduled. So reminder to @njestes or I to ping those guys once you've got it set up and we've checked that it's working @DanielJBeckman

**Comment by DanielJBeckman** [comment]
Ok. Let me log in and get that guy going.

**Comment by DanielJBeckman** [comment]
Wrote it in C++ but then had to down grade to shell. basically:
C:\
del /F /Q /S "Path\*"

**Comment by aaronstephenson** [comment]
@DanielJBeckman please schedule that script to run nightly using Windows Task Scheduler

**Comment by DanielJBeckman** [comment]
Done. Every night at 2AM EST

**Comment by HansVraga** [comment]
Want to close after the script runs successfully.

**Comment by DanielJBeckman** [comment]
Script is working great. run occures every night at 2 AM EST
