### ISSUE TITLE
Increase C drive on FWSPrimary and FWSPublicServices

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/swi#174]
Issue with the C drive filling up on FWSPublicServices and bringing AGS services to a slow crawl and causing timeouts.

**Comment by DanielJBeckman** [comment]
Boosted c volumes on FWSpub and FWSprod to 200 GiB. System is still initializing. We should do a health check in one week.

**Comment by HansVraga** [comment]
FWS emailed to report services are once again not responding.

@njestes found C: is full again

**Comment by njestes** [comment]
Was able to remove all of about 200 MB this morning and it's now down to ~90 MB free. FWSPublic had this issue earlier this month and even an increase of 60 GB then only bought us time until now. May need to figure out another approach to this. There must be some directory that AGS is filling up with now expendable data. I'm going to restart the AGS service to see if that flushes any kind of cache.

**Comment by njestes** [comment]
Doesn't seem to have done anything. Could a full restart of the instance potentially help flush any temp/cache data?

**Comment by DanielJBeckman** [comment]
When FWSPrimary becomes an issue again we can revisit this. For now FWSPublicServices is fixed and FWSPrimary is not having memory issues
