### ISSUE TITLE
Request for elevated AWS privileges on FWS account

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/swi#181]
Need the ability to start/stop instances at a minimum. Not sure what other privileges may be useful to me, but would welcome discussion to help determine.

**Comment by aaronstephenson** [comment]
Maybe create AMIs and volume snapshots and volumes, and swapping volumes?

**Comment by njestes** [comment]
These definitely would be useful. Will likely need a tutorial to go with them.

**Comment by aaronstephenson** [comment]
Looks like you already had stop/start permissions, so I just added permissions to create/delete AMIs, snapshots, and volumes. Let me know if you need anything else.
