### ISSUE TITLE
Modify the Wetlands tab in pop-up query

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/swi#70]
**See update in comments below** (keeping image for reference)

![image](https://cloud.githubusercontent.com/assets/12058013/18636879/68c3dbfc-7e58-11e6-8888-d1877fa2ef74.png)

modify the 'Wetland' tab to be:

**Comment by HansVraga** [comment]
Mitch plans to add a bit more on the Reports and 'More Info' tab.

**Comment by HansVraga** [comment]
Nick,

The general idea is a multi-tab 'modal' that pops up when a wetland polygon is identified.  Similar to https://fim.wim.usgs.gov/fim-js-dev/

Currently I don't think it needs a title bar, but just tabs.  Current tabs would be titled 'General', 'Reports' and 'About'.  Although Jane thought the title bar could be " <Wetland_Type> Habitat"

First (Default) tab is 'General'

It should read:

This <Acres> acre <Wetland_type> habitat is classified as a <Attribute>.  For a complete description click here. (link to decoder with pre-populated field)
 This area was photo interpreted using 1:<Image_scale>, <Source_Type> imagery from <Image_Date>.  Click here for project specific mapping conventions and information. (links to SuppMapInfo field from the Wetlands_Project_Metadata feature class at click location) 

Logic added......If <Image_Date> = 0 then insert text 'Link'  and link to 'https://www.fws.gov/wetlands/Documents/Scalable-Wetland-Mapping-Fact-Sheet.pdf'

This would also have to be implemented for the Riparian dataset as it is in the current query pop-up.   It would be the same text and fields, but from the riparian feature classes if they are checked on in the Mapper.   


Second tab is 'Reports'

This one will link to our document library via a spatial query.   This may be a formatting challenge as some areas may have a lot of documents (especially 'National').   I will let you play and design, but main Categories may expand upon click to include info.....

Text should read:

Below are links to wetland related documents for this area.
 
Historic Map Information (present if the spatial query is has a feature in 'Wetlands_Historic_Map_Info', may be multiple records, Name will be <PDF_Name> and link to <PDF_Hyberlink>

Title for next section(s) would depend on what is returned from the spatial query, with title coming from <Location> field in the Wetland_Documents feature class.  (will need to rename the feature class from Wetlands_Wetland_Documents to Wetland_Documents)

National
Regional
State
County
Local

The returns would include fields from feature class including <Title> with link to <URL> and <Year>  may consider <Author> but I fear we are running out of real estate.


Third tab is 'About'

Text should read:

Data Limitations
The Service's objective of mapping wetlands and deepwater habitats is to produce reconnaissance level information on the location, type and size of these resources. The maps are prepared from the analysis of high altitude imagery. Wetlands are identified based on vegetation, visible hydrology and geography. A margin of error is inherent in the use of imagery; thus, detailed on-the-ground inspection of any particular site may result in revision of the wetland boundaries or classification established through image analysis. Wetlands or other mapped features may have changed since the date of the imagery and/or field work. There may be occasional differences in polygon boundaries or classifications between the information depicted on the map and the actual conditions on site.

 Wetland Regulations

The wetlands displayed on the Wetlands Mapper show wetland type and extent using a biological definition of wetlands. There is no attempt to define the limits of proprietary jurisdiction of any Federal, State, or local government, or to establish the geographical scope of the regulatory programs of government agencies.  Persons intending to engage in activities involving modifications within or adjacent to wetland areas should seek the advice of appropriate federal, state, or local agencies concerning specified agency regulatory programs and proprietary jurisdictions that may affect such activities.

For information about regulations that may affect wetlands or development on your property, contact the U.S. Army Corps of Engineers office nearest you: http://www.usace.army.mil/Locations.aspx.


.Then can we have links to: About Application, Disclaimer, Data Limitations, Wetlands Geodatabase User Caution

Can it link/jump to to the tabs of the 'About' icon of the mapper?  (i.e. About Application, Disclaimer, Data Limitations, Wetlands Geodatabase User Caution)

Maybe also a link to our FAQs page.  https://www.fws.gov/wetlands/FAQs.html



Mitch Bergeson

**Comment by njestes** [comment]
this is covered in several smaller tasks now
