### ISSUE TITLE
Reversing Lat/Long in Geosearch can break application

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/swi#80]
Entering this example: 43.057100, -89.468096 into the Geosearch box appears to break the interface.
Reported by FWS, confirmed issue on my end (on Chrome)

**Comment by njestes** [comment]
@HansVraga we're done with this right?

**Comment by njestes** [comment]
Need to handle the error. I think it has to do with the geocoder returning non-numbers ("NaN")
