### ISSUE TITLE
https:// errors on load

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/swi#93]
Non-breaking errors, but some oddities when the page loads. @njestes did a bit of investigating already and think this may deal with the styles.

![image](https://cloud.githubusercontent.com/assets/12058013/25730022/94f97d64-3107-11e7-8079-cc66257ab186.png)

**Comment by HansVraga** [comment]
@mitch-wim can you take a look?

**Comment by mitch-wim** [comment]
Easier to just let you know about the fix so you can get it next time you're working on it instead of creating a branch then merging it...

Open src/styles/base.css

Second line of the file, make sure the import for Ionicons is HTTPS... so just add an S

@njestes

**Comment by njestes** [comment]
@mitch-wim having a weird thing with this that I remember from before. I have added the 's' to the reference in the base.css file, but when I build, it reverts to http.

I think the way we have it set up is that it's overwriting the src/styles/base.css with the bower_components version, so I think we should update the wim-styles that it's pulling from git to remedy that. If you can quickly take care of that, it would be great, but I can try to tackle it later. Just not a high priority for me right now.
